version: '3'

services:
  backend_spring:
    restart: on-failure
    networks:
      - devops
    image: rayenbenslimen/kaddem:1.0
    ports:
      - "8089:8089"
    depends_on:
      - mysqldb

  mysqldb:
    restart: on-failure
    networks:
      - devops
    container_name: mysqldb
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3307"
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
networks:
  devops:
    driver: bridge