version: '3.8'

networks:
  devops:
    driver: bridge

volumes:
  db:

services:
  db:
    container_name: db
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    image: mysql:5.7
    networks:
      - devops
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  backend:
    restart: on-failure
    container_name: backend
    depends_on:
      - db
    image: lindabelhadj/kaddem:1.0
    networks:
      - devops
    ports:
      - "8089:8089"
