version: '3'

services:
  backend_spring:
    image: rayenbenslimen/kaddem:1.0
    ports:
      - "8089:8089"
    depends_on:
      - mysqldb
    volumes:
      - ./backend_spring_data:/app/data

  mysqldb:
    container_name: mysqldb
    image: arm64v8/mysql:8.0.34
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'khaddemApp'
    ports:
      - "3307:3307"
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
